#pragma once

#include <fake-jni/fake-jni.h>

#include "stud/android_framework_stubs.h"
#include "stud/linker.h"

#include <nlohmann/json.hpp>

#include <sys/stat.h>

#include <cstdio>
#include <filesystem>
#include <functional>
#include <fstream>
#include <map>
#include <string>
#include <system_error>

// Real Djinni protocol-interface platform stubs (see the engineering notes'
// "scope out the Djinni protocol bindings work" entry for the full,
// evidence-based scoping this implements against). Every Roblox
// "platforminterface" protocol is a real, confirmed `<X>Core`/
// `IPlatform<X>` pair generated by Snap's open-source Djinni framework:
// `IPlatform<X>` is the Java-implemented side (native code calls INTO
// whatever object gets registered); `<X>Core.setPlatformImpl(IPlatform<X>)`
// is a real, exported, static native function real DEX code is supposed
// to call once to register that object. Stud never runs DEX, so this
// registration call has never happened for ANY of these protocols in
// this project's entire history, not a missing stub class exactly,
// but a missing registration *call*, exactly like the already-fixed
// `NativeGLJavaInterface.setAppBridgeNotificationListener` gap
// (game_activity_stubs.h) was. This file's job is to make that same
// real call ourselves, for real protocols, with a real stub object.
//
// `systemdialog` is deliberately NOT implemented here: real, confirmed
// against the library's exported symbols against the actual libroblox.so, it has NO exported
// `setPlatformImpl` symbol at all (unlike every protocol below),
// `IPlatformSystemDialogHandler` itself has its own real `CppProxy`,
// suggesting a different (constructor-injection or similar)
// registration mechanism this session didn't trace. Real, honest open
// item, don't add a stub for it without first finding the real
// injection point, or it'll sit registered but never actually reached.
namespace stud::jni_bridge {

// com.roblox.protocols.appagesignalsplatforminterface.generated.
// IPlatformAppAgeSignals. Real, confirmed against the app's own code method surface (two
// no-arg boolean queries). Honest `false` defaults for both, matching
// the real base class's own "no platform impl" fallback bodies exactly
// (`return false;` in the real `IPlatformAppAgeSignals`).
// Stud has no real app-age-signal source, so "not available" is the
// honest answer, not a fabricated one.
class AppAgeSignalsPlatformStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME(
        "com/roblox/protocols/appagesignalsplatforminterface/generated/IPlatformAppAgeSignals")
    FakeJni::JBoolean getAgeSignal() { return false; }
    FakeJni::JBoolean isAgeSignalAvailable() { return false; }
};

// com.roblox.protocols.bugreporterplatforminterface.generated.
// IPlatformBugReporter. Real, confirmed against the app's own code: a single no-arg boolean
// query. Honest `false` (matches the real base class's own default).
class BugReporterPlatformStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME(
        "com/roblox/protocols/bugreporterplatforminterface/generated/IPlatformBugReporter")
    FakeJni::JBoolean isAvailable() { return false; }
};

// com.roblox.protocols.pinshortcutplatforminterface.generated.
// IPlatformPinShortcut. Real, confirmed against the app's own code: `isAvailable()` (honest
// false) and `pinExperience(long,String,String)` (honest no-op; Stud
// has no real home-screen shortcut integration).
class PinShortcutPlatformStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME(
        "com/roblox/protocols/pinshortcutplatforminterface/generated/IPlatformPinShortcut")
    FakeJni::JBoolean isAvailable() { return false; }
    void pinExperience(FakeJni::JLong /*universeId*/, std::shared_ptr<FakeJni::JString> /*name*/,
                        std::shared_ptr<FakeJni::JString> /*iconUrl*/) {}
    // Real, live-caught addition, and a real lesson about working from
    // an older copy of the app. This protocol was the LAST of the six still failing to
    // register, and the engine's own Djinni glue named the cause exactly:
    //   djinni (djinni_support.cpp:339): GetMethodID returned null
    //   ... IPlatformPinShortcut.getDesiredThumbnailFormat ()Ljava/lang/String;
    // That method does not exist in the older copy of this class that
    // this project had been reading. That copy is of an OLDER APK,
    // while the configured libroblox.so is 2.736.1408. **A stale copy is not
    // automatically current; check it against the live binary before
    // treating "the method isn't there" as meaning it isn't
    // real.** An empty string is the honest answer here: it means "no
    // preferred thumbnail format", and Stud pins no shortcuts at all
    // (isAvailable() is false), so no real format could be stated.
    std::shared_ptr<FakeJni::JString> getDesiredThumbnailFormat() {
        return std::make_shared<FakeJni::JString>("");
    }
    // Same shape again, one APK later: 2.738 asks for this one too.
    // False for the same reason as isAvailable(), there is no desktop
    // equivalent of a pinned home-screen shortcut to reveal.
    FakeJni::JBoolean isRevealPinnedExperienceAvailable() { return false; }
    // The action behind the flag above. Nothing to do: there is no
    // pinned shortcut to reveal, and isRevealPinnedExperienceAvailable()
    // says so, so a caller that respects it never gets here.
    void revealPinnedExperience(FakeJni::JLong /*universeId*/) {}
    // The rest of this protocol's surface, taken from the CONFIGURED
    // APK's own copy of the class rather than discovered one failed
    // registration at a time: 2.738 adds a V2 pin call and a flag for
    // whether Lua should show a notification afterwards. All false/no-op
    // for the same reason as isAvailable(), a desktop has no home
    // screen to pin an experience to.
    FakeJni::JBoolean isPinExperienceV2Available() { return false; }
    void pinExperienceV2(FakeJni::JLong /*universeId*/, FakeJni::JLong /*placeId*/,
                         std::shared_ptr<FakeJni::JString> /*name*/,
                         std::shared_ptr<FakeJni::JString> /*iconUrl*/) {}
    FakeJni::JBoolean shouldShowLuaNotificationOnPinExperienceCompleted() { return false; }
};

// com.roblox.protocols.devicedisplayplatforminterface.generated.
// DeviceDisplayCapability: real Java enum (BRIGHTNESS, WAKELOCK), used
// as a real JNI *object* parameter type (Djinni enums are real Java enum
// instances at the JNI boundary, not raw ints), registered here purely
// so `hasCapability`'s own real parameter-type signature matches for
// GetMethodID resolution. No enum constants modeled yet (nothing on
// Stud's side constructs one to pass in either direction currently),
// grow against real evidence if that changes.
class DeviceDisplayCapabilityStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME(
        "com/roblox/protocols/devicedisplayplatforminterface/generated/DeviceDisplayCapability")
};

// com.roblox.protocols.devicedisplayplatforminterface.generated.
// IPlatformDeviceDisplayHandler. Real, confirmed against the app's own code 6-method
// surface. Honest defaults throughout, matching the real base class's
// own fallback bodies exactly (0.0f brightness, false for both
// availability queries, no-op setters).
class DeviceDisplayPlatformStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME(
        "com/roblox/protocols/devicedisplayplatforminterface/generated/"
        "IPlatformDeviceDisplayHandler")
    FakeJni::JFloat getBrightness() { return 0.0f; }
    FakeJni::JBoolean hasCapability(std::shared_ptr<DeviceDisplayCapabilityStub> /*capability*/) {
        return false;
    }
    FakeJni::JBoolean isAvailable() { return false; }
    void setBrightness(FakeJni::JFloat /*value*/) {}
    void setBrightnessToDefault() {}
    void setKeepAwake(FakeJni::JBoolean /*keepAwake*/) {}
};

// com.roblox.protocols.localstorageplatforminterface.generated.
// IPlatformLocalStorageHandler. Real, confirmed against the app's own code 13-method
// surface (secure per-user key/value storage). Honest defaults
// throughout (false/null/0), matching the real base class's own
// fallback bodies exactly. `getUsers()`'s real return type is
// `HashSet<Long>`, previously an honest-but-signature-mismatched
// `nullptr` (a generic `JObject` return computes a `Ljava/lang/Object;`
// signature, not the real `Ljava/util/HashSet;` one jnivm's method
// resolution matches against). Fixed now that `android_framework_
// stubs.h` has a real, functional `JavaUtilHashSetStub` registered
// under the correct name, returns a real, empty (not fabricated-
// nonempty) HashSet, with the real, correctly-matching signature.
// Real, live-caught gap (the engineering notes): every Djinni protocol's
// `setPlatformImpl` call was recorded as succeeding because it returned
// without trapping, but each one left a PENDING JNI EXCEPTION behind,
// because Djinni's own JNI glue does a real
// `FindClass("<Interface>$CppProxy")` during registration and that inner
// class was never registered (`raw jclass=0x0`, live-confirmed for all
// six protocols). So none of the platform implementations were ever
// actually installed: which is why, for example, the real Lua app
// never once asked Stud's LocalStorage handler who was signed in, and
// routed to the logged-out `Landing` screen instead of `Home`.
//
// These are the real, minimal `$CppProxy` inner classes. Djinni
// generates them to wrap a native object for Java; Stud never needs to
// instantiate one (nothing here hands a C++ object back to Java), so
// they only need to exist and carry the real class name.
class AppAgeSignalsCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/appagesignalsplatforminterface/generated/IPlatformAppAgeSignals$CppProxy")

    // Djinni's own glue caches these two off the CppProxy class during
    // registration and throws java.lang.Error if either is missing,
    // which is exactly what was making every setPlatformImpl() fail.
    // Real shapes from the real class: `private CppProxy(long)`
    // and `public static native void nativeDestroy(long)`.
    AppAgeSignalsCppProxyStub() = default;
    explicit AppAgeSignalsCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    // Real field Djinni's glue looks up by name during registration
    // (`private final long nativeRef` in the real CppProxy).
    // Missing it was the actual failure:
    // "djinni (djinni_support.cpp:352): GetFieldID returned null".
    FakeJni::JLong nativeRef = 0;
};

// systemdialog is the one protocol with no native setPlatformImpl entry
// point (see this file's header comment), so its CppProxy was never
// registered alongside the other six. That was invisible until
// PlatformSystemDialogHandler.INSTANCE started resolving: with the real
// singleton reachable, Djinni's own glue goes on to look this inner
// class up and threw `djinni::jni_exception` when it was absent,
// live-caught as `RBXCRASH: UnhandledException (djinni::jni_exception)`
// during boot, which left the Lua app never routing anywhere.
class SystemDialogCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/systemdialogplatforminterface/generated/IPlatformSystemDialogHandler$CppProxy")

    SystemDialogCppProxyStub() = default;
    explicit SystemDialogCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    FakeJni::JLong nativeRef = 0;
};

class BugReporterCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/bugreporterplatforminterface/generated/IPlatformBugReporter$CppProxy")

    // Djinni's own glue caches these two off the CppProxy class during
    // registration and throws java.lang.Error if either is missing,
    // which is exactly what was making every setPlatformImpl() fail.
    // Real shapes from the real class: `private CppProxy(long)`
    // and `public static native void nativeDestroy(long)`.
    BugReporterCppProxyStub() = default;
    explicit BugReporterCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    // Real field Djinni's glue looks up by name during registration
    // (`private final long nativeRef` in the real CppProxy).
    // Missing it was the actual failure:
    // "djinni (djinni_support.cpp:352): GetFieldID returned null".
    FakeJni::JLong nativeRef = 0;
};

class DesignFoundationsCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/designfoundationsplatforminterface/generated/IPlatformDesignFoundations$CppProxy")

    // Djinni's own glue caches these two off the CppProxy class during
    // registration and throws java.lang.Error if either is missing,
    // which is exactly what was making every setPlatformImpl() fail.
    // Real shapes from the real class: `private CppProxy(long)`
    // and `public static native void nativeDestroy(long)`.
    DesignFoundationsCppProxyStub() = default;
    explicit DesignFoundationsCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    // Real field Djinni's glue looks up by name during registration
    // (`private final long nativeRef` in the real CppProxy).
    // Missing it was the actual failure:
    // "djinni (djinni_support.cpp:352): GetFieldID returned null".
    FakeJni::JLong nativeRef = 0;
};

class DeviceDisplayCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/devicedisplayplatforminterface/generated/IPlatformDeviceDisplayHandler$CppProxy")

    // Djinni's own glue caches these two off the CppProxy class during
    // registration and throws java.lang.Error if either is missing,
    // which is exactly what was making every setPlatformImpl() fail.
    // Real shapes from the real class: `private CppProxy(long)`
    // and `public static native void nativeDestroy(long)`.
    DeviceDisplayCppProxyStub() = default;
    explicit DeviceDisplayCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    // Real field Djinni's glue looks up by name during registration
    // (`private final long nativeRef` in the real CppProxy).
    // Missing it was the actual failure:
    // "djinni (djinni_support.cpp:352): GetFieldID returned null".
    FakeJni::JLong nativeRef = 0;
};

class LocalStorageCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/localstorageplatforminterface/generated/IPlatformLocalStorageHandler$CppProxy")

    // Djinni's own glue caches these two off the CppProxy class during
    // registration and throws java.lang.Error if either is missing,
    // which is exactly what was making every setPlatformImpl() fail.
    // Real shapes from the real class: `private CppProxy(long)`
    // and `public static native void nativeDestroy(long)`.
    LocalStorageCppProxyStub() = default;
    explicit LocalStorageCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    // Real field Djinni's glue looks up by name during registration
    // (`private final long nativeRef` in the real CppProxy).
    // Missing it was the actual failure:
    // "djinni (djinni_support.cpp:352): GetFieldID returned null".
    FakeJni::JLong nativeRef = 0;
};

class PinShortcutCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/pinshortcutplatforminterface/generated/IPlatformPinShortcut$CppProxy")

    // Djinni's own glue caches these two off the CppProxy class during
    // registration and throws java.lang.Error if either is missing,
    // which is exactly what was making every setPlatformImpl() fail.
    // Real shapes from the real class: `private CppProxy(long)`
    // and `public static native void nativeDestroy(long)`.
    PinShortcutCppProxyStub() = default;
    explicit PinShortcutCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    // Real field Djinni's glue looks up by name during registration
    // (`private final long nativeRef` in the real CppProxy).
    // Missing it was the actual failure:
    // "djinni (djinni_support.cpp:352): GetFieldID returned null".
    FakeJni::JLong nativeRef = 0;
};

// The `<X>Core$CppProxy` half of each protocol. Djinni resolves BOTH
// the platform interface's CppProxy and the Core's during registration
// live-confirmed, the Core one was the next
// "djinni (djinni_support.cpp:313): FindClass returned null" after the
// platform-side proxies were added. Same real shape.
class AppAgeSignalsCoreCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/appagesignalsplatforminterface/generated/IAppAgeSignalsCore$CppProxy")

    AppAgeSignalsCoreCppProxyStub() = default;
    explicit AppAgeSignalsCoreCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    FakeJni::JLong nativeRef = 0;
};

class BugReporterCoreCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/bugreporterplatforminterface/generated/IBugReporterCore$CppProxy")

    BugReporterCoreCppProxyStub() = default;
    explicit BugReporterCoreCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    FakeJni::JLong nativeRef = 0;
};

class PinShortcutCoreCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/pinshortcutplatforminterface/generated/IPinShortcutHandlerCore$CppProxy")

    PinShortcutCoreCppProxyStub() = default;
    explicit PinShortcutCoreCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    FakeJni::JLong nativeRef = 0;
};

class DeviceDisplayCoreCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/devicedisplayplatforminterface/generated/IDeviceDisplayHandlerCore$CppProxy")

    DeviceDisplayCoreCppProxyStub() = default;
    explicit DeviceDisplayCoreCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    FakeJni::JLong nativeRef = 0;
};

class LocalStorageCoreCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/localstorageplatforminterface/generated/ILocalStorageHandlerCore$CppProxy")

    LocalStorageCoreCppProxyStub() = default;
    explicit LocalStorageCoreCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    FakeJni::JLong nativeRef = 0;
};

class DesignFoundationsCoreCppProxyStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME("com/roblox/protocols/designfoundationsplatforminterface/generated/IDesignFoundationsCoreListener$CppProxy")

    DesignFoundationsCoreCppProxyStub() = default;
    explicit DesignFoundationsCoreCppProxyStub(FakeJni::JLong native_ref) : nativeRef(native_ref) {}
    static void nativeDestroy(FakeJni::JLong /*native_ref*/) {}

    FakeJni::JLong nativeRef = 0;
};

class LocalStoragePlatformStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME(
        "com/roblox/protocols/localstorageplatforminterface/generated/"
        "IPlatformLocalStorageHandler")
    // Real, working implementation, not honest-default stubs any more.
    //
    // Why this matters (live-traced, the engineering notes): the real Lua app
    // asks the platform who is logged in via this protocol. Returning 0
    // from getCurrentUser() and null from getSecureValueForCurrentUser()
    // tells the app there is no signed-in user, which is exactly why it
    // routed to the logged-out `Landing` screen instead of `Home` even
    // with a real, valid session cookie present.
    //
    // Backed by a real in-memory store, seeded from Stud's own real
    // authenticated identity (see set_real_current_user() /
    // seed_secure_value() below, called from main.cpp). Every key the
    // engine asks for is logged BY NAME ONLY, never the value, which
    // is a real credential.
    FakeJni::JBoolean deleteCurrentUserValues() {
        store().erase(current_user());
        persist();
        return true;
    }
    FakeJni::JBoolean deleteSecureValue(std::shared_ptr<FakeJni::JString> key) {
        if (key) store()[current_user()].erase(key->asStdString());
        persist();
        return true;
    }
    FakeJni::JBoolean deleteUserValues(FakeJni::JLong userId) {
        store().erase(static_cast<long long>(userId));
        persist();
        return true;
    }
    FakeJni::JLong getCurrentUser() { return static_cast<FakeJni::JLong>(current_user()); }
    std::shared_ptr<FakeJni::JString> getSecureValue(std::shared_ptr<FakeJni::JString> key) {
        return lookup(current_user(), key, "getSecureValue");
    }
    std::shared_ptr<FakeJni::JString> getSecureValueForCurrentUser(
        std::shared_ptr<FakeJni::JString> key) {
        return lookup(current_user(), key, "getSecureValueForCurrentUser");
    }
    std::shared_ptr<FakeJni::JString> getSecureValueForUser(std::shared_ptr<FakeJni::JString> key,
                                                             FakeJni::JLong userId) {
        return lookup(static_cast<long long>(userId), key, "getSecureValueForUser");
    }
    // Every account this install knows about. This is how the app's own
    // account switcher enumerates them, an empty set means "no other
    // accounts", so a second sign-in would appear to replace the first
    // rather than sit alongside it. The store is already keyed by user
    // id and persisted that way, so the real answer is simply its keys.
    std::shared_ptr<JavaUtilHashSetStub> getUsers() {
        auto users = std::make_shared<JavaUtilHashSetStub>();
        for (const auto& [user, values] : store()) {
            if (user == 0 || values.empty()) continue;
            users->add(std::make_shared<JavaLangLongStub>(static_cast<FakeJni::JLong>(user)));
        }
        std::printf("stud: LocalStorage.getUsers() -> %d account(s)\n",
                    static_cast<int>(users->size()));
        std::fflush(stdout);
        return users;
    }
    FakeJni::JBoolean setCurrentUser(FakeJni::JLong userId) {
        current_user() = static_cast<long long>(userId);
        std::printf("stud: LocalStorage.setCurrentUser(%lld)\n", current_user());
        std::fflush(stdout);
        persist();
        return true;
    }
    FakeJni::JBoolean setSecureValue(std::shared_ptr<FakeJni::JString> key,
                                      std::shared_ptr<FakeJni::JString> value) {
        return store_value(current_user(), key, value, "setSecureValue");
    }
    FakeJni::JBoolean setSecureValueForCurrentUser(std::shared_ptr<FakeJni::JString> key,
                                                    std::shared_ptr<FakeJni::JString> value) {
        return store_value(current_user(), key, value, "setSecureValueForCurrentUser");
    }

    // Seeding hooks, called once at bring-up from main.cpp with Stud's
    // own real, already-authenticated identity.
    //
    // Seeding never overwrites what was restored from disk. Process A
    // authenticates with the one cookie the keyring holds, so its idea of
    // "the" user is whichever account that cookie belongs to, but the
    // user may have switched accounts inside the app since, and the store
    // is the record of that. Letting the seed win would silently drag the
    // app back to the earlier account on every launch, and would
    // overwrite that account's stored session with an older copy.
    static void set_real_current_user(long long user_id) {
        if (current_user() != 0) {
            std::printf("stud: LocalStorage keeping the restored current user id=%lld (launch "
                        "identity id=%lld)\n",
                        current_user(), user_id);
            std::fflush(stdout);
            return;
        }
        current_user() = user_id;
        std::printf("stud: LocalStorage seeded current user id=%lld\n", user_id);
        std::fflush(stdout);
    }
    static void seed_secure_value(long long user_id, const std::string& key,
                                   const std::string& value) {
        auto& slot = store()[user_id][key];
        if (!slot.empty()) {
            std::printf("stud: LocalStorage already has key=\"%s\" for user=%lld, keeping it\n",
                        key.c_str(), user_id);
            std::fflush(stdout);
            return;
        }
        slot = value;
        std::printf("stud: LocalStorage seeded secure value key=\"%s\" for user=%lld (%zu bytes)\n",
                    key.c_str(), user_id, value.size());
        std::fflush(stdout);
        persist();
    }

    // Real persistence. Without it every login is forgotten the moment
    // Stud exits: the engine writes the signed-in user and its session
    // material here, and reads them back on the next launch to decide
    // whether to route to Home or to the logged-out screen (its own
    // `cachedUserId`, live-traced as the exact input to that
    // decision). A real device persists this the same way; keeping it in
    // memory made Stud permanently "first launch, nobody signed in".
    //
    // This holds a real session credential per account, so it does NOT
    // go to a file of its own. It goes through Stud's safe storage,
    // encrypted at rest, with the key in the system keyring, via the
    // hooks below, which the owning process wires to whatever can reach
    // the keyring from where it runs. Values are never logged.
    static void set_storage_hooks(std::function<void(const std::string&)> save,
                                   std::function<std::string()> load_hook) {
        saver() = std::move(save);
        loader() = std::move(load_hook);
    }

    static void load() {
        auto& load_hook = loader();
        if (!load_hook) return;
        load_from(load_hook());
    }

    // Writes the current document out through the save hook. Public so a
    // one-time migration can commit what it just imported.
    static void save_now() { persist(); }

    // Parses a previously persisted document. Public so a one-time
    // migration off an older plaintext file can feed it in.
    static void load_from(const std::string& text) {
        if (text.empty()) return;
        nlohmann::json doc;
        try {
            doc = nlohmann::json::parse(text);
        } catch (const std::exception& e) {
            std::fprintf(stderr, "stud: LocalStorage: ignoring unreadable store (%s)\n", e.what());
            return;
        }
        if (!doc.is_object()) return;
        current_user() = doc.value("currentUser", 0LL);
        size_t restored = 0;
        if (doc.contains("users") && doc["users"].is_object()) {
            for (auto& [user_key, values] : doc["users"].items()) {
                if (!values.is_object()) continue;
                long long user = 0;
                try {
                    user = std::stoll(user_key);
                } catch (const std::exception&) {
                    continue;
                }
                for (auto& [k, v] : values.items()) {
                    if (!v.is_string()) continue;
                    store()[user][k] = v.get<std::string>();
                    ++restored;
                }
            }
        }
        std::printf("stud: LocalStorage restored: current user=%lld, %zu value(s) across %zu "
                    "account(s)\n",
                    current_user(), restored, store().size());
        std::fflush(stdout);
    }

private:
    static std::function<void(const std::string&)>& saver() {
        static std::function<void(const std::string&)> f;
        return f;
    }
    static std::function<std::string()>& loader() {
        static std::function<std::string()> f;
        return f;
    }

    static void persist() {
        auto& save = saver();
        if (!save) return;
        nlohmann::json doc;
        doc["currentUser"] = current_user();
        nlohmann::json users = nlohmann::json::object();
        for (const auto& [user, values] : store()) {
            nlohmann::json entry = nlohmann::json::object();
            for (const auto& [k, v] : values) entry[k] = v;
            users[std::to_string(user)] = std::move(entry);
        }
        doc["users"] = std::move(users);
        save(doc.dump());
    }

    static long long& current_user() {
        static long long id = 0;
        return id;
    }
    static std::map<long long, std::map<std::string, std::string>>& store() {
        static std::map<long long, std::map<std::string, std::string>> s;
        return s;
    }
    static std::shared_ptr<FakeJni::JString> lookup(long long user,
                                                     const std::shared_ptr<FakeJni::JString>& key,
                                                     const char* what) {
        if (!key) return nullptr;
        std::string k = key->asStdString();
        auto user_it = store().find(user);
        bool found = user_it != store().end() && user_it->second.count(k) != 0;
        // Key name only, the value is a real credential.
        std::printf("stud: LocalStorage.%s(key=\"%s\", user=%lld) -> %s\n", what, k.c_str(), user,
                    found ? "hit" : "MISS");
        std::fflush(stdout);
        if (!found) return nullptr;
        return std::make_shared<FakeJni::JString>(user_it->second[k]);
    }
    static FakeJni::JBoolean store_value(long long user,
                                          const std::shared_ptr<FakeJni::JString>& key,
                                          const std::shared_ptr<FakeJni::JString>& value,
                                          const char* what) {
        if (!key) return false;
        std::string k = key->asStdString();
        store()[user][k] = value ? value->asStdString() : std::string();
        std::printf("stud: LocalStorage.%s(key=\"%s\", user=%lld) stored\n", what, k.c_str(), user);
        std::fflush(stdout);
        persist();
        return true;
    }

public:
    FakeJni::JBoolean setSecureValueForUser(std::shared_ptr<FakeJni::JString> /*key*/,
                                             std::shared_ptr<FakeJni::JString> /*value*/,
                                             FakeJni::JLong /*userId*/) {
        return false;
    }
};

// com.roblox.protocols.designfoundationsplatforminterface.generated.
// DesignTokens; real record class (RGBA/ColorTokenVariants-backed
// theming data). Registered purely for `onTokensUpdated`'s own real
// parameter-type signature to match; Stud has no real design-token
// consumer yet, so no fields modeled (grow against real evidence).
class DesignTokensStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME(
        "com/roblox/protocols/designfoundationsplatforminterface/generated/DesignTokens")
};

// com.roblox.protocols.designfoundationsplatforminterface.generated.
// IPlatformDesignFoundations: real, confirmed against the app's own code 2-method surface,
// both honest no-ops (matches the real base class's own default body).
class DesignFoundationsPlatformStub : public FakeJni::JObject {
public:
    DEFINE_CLASS_NAME(
        "com/roblox/protocols/designfoundationsplatforminterface/generated/"
        "IPlatformDesignFoundations")
    void onTokensCleared() {}
    void onTokensUpdated(std::shared_ptr<DesignTokensStub> /*tokens*/) {}
};

// Registers every protocol-platform stub class above onto `jvm`, same
// timing requirement as register_android_framework_stubs()/
// register_game_activity_stubs() (before dlopen(), see
// process-b/src/main.cpp's own doc comment on why).
void register_protocol_platform_stubs(FakeJni::Jvm& jvm);

struct ProtocolPlatformBootstrapResult {
    bool app_age_signals_set_platform_impl_called = false;
    bool app_age_signals_set_platform_impl_trapped_abort = false;
    bool bug_reporter_set_platform_impl_called = false;
    bool bug_reporter_set_platform_impl_trapped_abort = false;
    bool pin_shortcut_set_platform_impl_called = false;
    bool pin_shortcut_set_platform_impl_trapped_abort = false;
    bool device_display_set_platform_impl_called = false;
    bool device_display_set_platform_impl_trapped_abort = false;
    bool local_storage_set_platform_impl_called = false;
    bool local_storage_set_platform_impl_trapped_abort = false;
    bool design_foundations_set_platform_impl_called = false;
    bool design_foundations_set_platform_impl_trapped_abort = false;
};

// Calls each real `<X>Core.setPlatformImpl(stub)` directly, the real
// registration DEX code would normally do, once, at real app startup.
// Symbols missing from this specific libroblox.so build are skipped
// individually, not a hard failure, matching every other bridge in this
// directory's own degrade-gracefully convention.
ProtocolPlatformBootstrapResult run_protocol_platform_stubs_bootstrap(
    FakeJni::Jvm& jvm, const stud::linker::LoadedLibrary& lib);

}  // namespace stud::jni_bridge
