#pragma once

// The flag names `nativeInitializeNativeFlags` expects as its input.
//
// A real device does not pass an empty array here, which is what Stud
// did for a long time. The app carries a compiled-in catalogue of flags
// and hands that entry point the subset registered on the native side,
// 142 of them, a fixed, build-time set rather than anything that depends
// on install state or stored preferences.
//
// Stud runs no DEX, so it cannot compute the subset the way the app
// does; the names are listed here instead. They are data the app itself
// would supply, checked, and they need regenerating whenever the
// configured APK changes, the engineering notes record how.
//
// Scope, honestly: this is only the input to that one call. It is not
// the much larger FFlag/DFFlag/FInt/FString namespace reached through
// nativeGetFFlag/nativeRegisterFFlag, which is a separate path that
// already exists in this codebase.

namespace stud::jni_bridge {

inline constexpr const char* kRealNativeFlagNames[] = {
    "EnableRedirectLegacyRatingPromptToGoogleNativePrompt",
    "EnableLegacyRatingPromptNewDesign",
    "DisableLegacyRatingPromptSubheader",
    "EnableRedirectLegacyRatingPromptToSurvey",
    "DisableLegacyRatingPrompt",
    "EnableGameActivity8",
    "EnableHasRobloxSubscriptionParse",
    "EnableToastMsgInGActivity",
    "EnableDeferredDeeplinkResolutionAndroidV2",
    "EnableAttributionContextRealtimeWriteV1",
    "EnableAttributionContextExtraFieldsV1",
    "EnableAttributionContextSkipReasonCountersV1",
    "EnableDeeplinkAttributionAdNameAndroidThreading",
    "EnableDeeplinkAttributionAdsetFallbackAndroid",
    "EnableAndroidUnlockOrientation",
    "EnableAndroidUnlockOrientationTabletOnly",
    "EnableAndroidBinaryChannelDownloadTiming",
    "EnableFeatureDeliveryRetry",
    "DeleteRoomDBEventsOnClientError",
    "UseGsonForEventUpload",
    "EnablePinnedShortcutsOnHomeScreenAndroid3",
    "EnableRecentlyPlayedWidgetAndroidShell6",
    "EnableRecentlyPlayedWidgetCounter",
    "AndroidEnableFlushingTelemetryV1Events",
    "AndroidEnableFlushingTelemetryV2Events",
    "AndroidEnableTelemetryFlushWorker2",
    "DownloadWebRtcSdkImmediately",
    "InitializeWebRtc",
    "EnableWebRtcOnDemandPathLoad",
    "EnableGmaSdkInitRoutingAndroid",
    "FixGmaSdkAdAttributionParsing",
    "EnableNewLocalStorageTelemetry",
    "FixGenericWebFragmentToolbarButtons",
    "EnableCLI198900_2",
    "UseABCEndpoint",
    "UseAndroidGooglePaymentsProtocolQueryPurchases",
    "UseAndroidPaymentsProtocolThrobber",
    "UseAndroidPaymentsProtocolThreadsafeSessionId",
    "FixAndroidPaymentsProtocolPurchaseFinishedNpe",
    "AndroidPaymentsProtocolUsePurchaseListenerForUserCancellation",
    "EnableAndroidGooglePaymentsProtocolV2V2",
    "EnableAndroidPaymentsProtocolPaymentSessionId",
    "FixAndroidWebDialogPaymentSessionId",
    "EnableIsolatedProcessLoadAdTimeout",
    "EnableAppRatingPromptAndroidShell3",
    "EnableGooglePlayGamesIntegration5",
    "EnablePGSAnalytics2",
    "UseMinutesForPGSStreaks",
    "PgsForceEnabled",
    "PgsExperimentEnabled",
    "PgsTreatmentActive",
    "EnableAppAgeSignalsOnAndroid",
    "AppAgeSignalsUseFakeManager",
    "EnableAndroidShareViaFileProvider",
    "EnableCookieManagerVersionB3",
    "EnableWebViewCameraPermission",
    "EnableAndroidDevBranchConfiguration",
    "EnableRichPushNotification2",
    "EnableRegisterBackgroundPushSettingsReportingOnPush",
    "DisablePauseSessionInPersonaFlow",
    "EnablePasskeySilentUpgradeForAndroid",
    "AddPowerSaverStats",
    "EnableNetworkStatusObserving",
    "EnableSystemDialogHandlerInAndroid",
    "EnableDeviceDisplayHandlerInAndroid",
    "EnableDisplayWakeLock",
    "EnableAppPlatformQoSEmergencyOnAndroidStartup",
    "EnableInitHelperNativeWrappers",
    "EnableAdditionalTTIEvents",
    "EnableAttachBaseContextMilestone",
    "AvoidCacheIfNetworkFaster",
    "RefreshAndroidCachedFlagsOnBackgroundFetch",
    "EnableSendNotificationSettingsOnPushAck",
    "RefreshRbxKeyboardAutofill2",
    "EnableAndroidPasskeyAvailabilityPreflight",
    "EnableAndroidWebViewService4",
    "FixKeyboardMinAdjustment",
    "FixKeyboardPositionReportingOffset",
    "VisiblePasswordIsText",
    "EnableAndroidSafeAreaInsetsInLuaApp",
    "EnableAndroidNavBarInSafeAreaInsets",
    "ExcludeKeyboardFromSafeAreaInsets",
    "EnableAndroidPasswordSuggestion2",
    "CachedFlagTTIMilestones",
    "EnableAutofillEvents",
    "CheckFlagCacheExpiry",
    "EnableAtomicDeferredIntentProcessing",
    "EnableDeeplinkReceivedExtendedCoverageAndroid2",
    "PassFlagSignatureToEngine",
    "EnableChannelsMigrationFirstPhase",
    "EnableChannelsMigrationSecondPhase3",
    "RevertNotificationChannelsMigration",
    "EnableNotificationChannelGrouping2",
    "EnableAndroidCallPushNotification",
    "UseExplicitStorePackageForIntents",
    "EnableSamsungIapNewVersionWithObfuscatedProfileId",
    "SkipChannelBurnOnBackgroundStart",
    "PTFDisablesPersonaSdk",
    "PTFDisableSurfaceViewRequestFocus",
    "EnableOnNativeAdPaidEventTelemetry",
    "EnableTextInputRestoreOnShowKeyboard",
    "StratusEnableSetStatusBarVisibility",
    "EnableHideAndroidStatusBarInLandscape",
    "CompressedFlagCache",
    "AndroidCompressedFlagCacheWrite",
    "RevertNewPasswordInputTypeChange",
    "AndroidWebViewFocusFix",
    "SkipFlagFetchWorkerAppForeground",
    "ShowHeaderForRobux",
    "PassFlagCacheEmptyPayloadToCpp",
    "EnableReportNotificationChannelsAsJson",
    "AndroidSendTouchEndVelocity",
    "AndroidProcessHistoricalTouchEvents",
    "AndroidGuardNullInputAdapter",
    "FixHapticProtocolCrash",
    "EnableInflateTracking",
    "StratusKeepScreenOn",
    "EnableGameStreamingOrientationChangeAndroid",
    "CrashWhenAppBridgeNotStarted",
    "EnableBackgroundOtaPolling",
    "DebugSkipInAppOtaDownload",
    "DebugSkipOtaPatchVerification",
    "BackgroundOtaPollingWifiOnly",
    "EnableWorkerBlobPromotion",
    "EnableDesignFoundations",
    "EnableGmaSdkAdapterTelemetry2",
    "EnableRewardedAdCallbackExceptionHandling",
    "EnableWebViewTelemetry",
    "EnablePayloadDrivenNotificationActions",
    "EnableRevisedAdsHelper",
    "OSGameSearchEnabled2",
    "OSGameSearchAccountSwitchFixEnabled",
    "OSSearchClickTelemetryEnabled",
    "EnableSignalCheckoutSessionIdOnPurchase",
    "GmasdkInstantInstallIxpEnabled",
    "EnableGameIdToExcludeParameterAndroid",
    "EnableKotlinAdsProtocol",
    "DisableAndroidLaunchTimeReporter",
    "DisableAndroidStopwatch",
    "MigrateJobQueueToCoroutinesAndroid",
    "EnableLazyWorkManagerInit",
    "RemoveInputListenerDeviceTimestamps",
};

inline constexpr int kRealNativeFlagNamesCount = 142;

}  // namespace stud::jni_bridge
