#!/usr/bin/env python3
"""Turn RAVU-Zoom's trained weight table into a header render-host embeds.

The table lives as one very long hex line at the end of
third_party/mpv-prescalers/ravu-zoom-r2-rgb.hook, under a //!TEXTURE
block that declares its size and format. Everything here is read from
that block rather than hardcoded, so a different variant of the hook
produces a correct header rather than a subtly wrong one.

One thing the hook gets wrong about itself, and it is worth knowing
before reading the assertion below: it declares //!FORMAT rgba16f, and
the data it carries is float32. That was settled by decoding rather than
assumed -- read as float16 the values come out as nonsense (-10136,
-1963), read as float32 all 186,624 of them fall inside [-4,4], and the
byte count matches float32 exactly. render-host uploads it as
R32G32B32A32_SFLOAT to match.

    gen_ravu_lut.py <hook> <out.h>
"""

import binascii
import sys


def main() -> int:
    if len(sys.argv) != 3:
        sys.stderr.write(__doc__)
        return 2
    hook_path, out_path = sys.argv[1], sys.argv[2]

    lines = open(hook_path).read().splitlines()
    width = height = None
    for line in lines:
        if line.startswith("//!SIZE"):
            width, height = (int(x) for x in line.split()[1:3])
    if width is None or height is None:
        sys.stderr.write(f"{hook_path}: no //!SIZE in the texture block\n")
        return 1

    raw = binascii.unhexlify(lines[-1].strip())
    expected = width * height * 4 * 4  # rgba, float32 each; see the docstring
    if len(raw) != expected:
        sys.stderr.write(
            f"{hook_path}: {len(raw)} bytes of table, expected {expected} "
            f"for {width}x{height} rgba float32\n")
        return 1

    words = len(raw) // 4
    with open(out_path, "w") as out:
        out.write("// Generated by tools/gen_ravu_lut.py. Do not edit.\n")
        out.write(f"// RAVU-Zoom r2 weights, {width}x{height} rgba float32.\n")
        out.write("{\n")
        for i in range(0, words, 8):
            chunk = raw[i * 4:(i + 8) * 4]
            vals = ["0x%08x" % int.from_bytes(chunk[j:j + 4], "little")
                    for j in range(0, len(chunk), 4)]
            out.write("    " + ",".join(vals) + ",\n")
        out.write("}\n")
    print(f"{out_path}: {words} words, {width}x{height}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
