#!/usr/bin/env python3
"""Turn RAVU-Zoom's trained weight table into a header render-host embeds.

The table lives as one very long hex line at the end of
third_party/mpv-prescalers/ravu-zoom-r2-rgb.hook, under a //!TEXTURE
block that declares its size and format. Everything here is read from
that block rather than hardcoded, so a different variant of the hook
produces a correct header rather than a subtly wrong one.

One thing the hook gets wrong about itself: it declares //!FORMAT
rgba16f, and the DATA it carries is float32. That was settled by
decoding rather than assumed -- read as float16 the values come out as
nonsense (-10136, -1963), read as float32 all 186,624 of them fall
inside [-4,4], and the byte count matches float32 exactly.

The format it declares is nonetheless the right one, and this converts
to it. mpv uploads these weights as half and the values are trained
against that, so float32 in the texture is twice the bytes for
precision the algorithm was never designed to use -- and those bytes
are read four times per output pixel, which is RAVU's dominant cost.
The conversion is checked rather than trusted: anything that would
overflow half, or lose more than a thousandth of its magnitude, is
reported and fails the build.

    gen_ravu_lut.py <hook> <out.h> [table]

`table` selects which //!TEXTURE block to emit, 0 by default. The
anti-ringing hooks carry two: the filter weights, and a second set used
to build the soft local minimum and maximum the result is clamped into.
"""

import binascii
import struct
import sys


def main() -> int:
    if len(sys.argv) not in (3, 4):
        sys.stderr.write(__doc__)
        return 2
    hook_path, out_path = sys.argv[1], sys.argv[2]
    wanted = int(sys.argv[3]) if len(sys.argv) == 4 else 0

    lines = open(hook_path).read().splitlines()

    # Each //!TEXTURE block declares a size and is followed by one very
    # long hex line. Read them in order rather than assuming there is
    # only one, which the anti-ringing variants break.
    tables = []
    pending = None
    for line in lines:
        if line.startswith("//!TEXTURE"):
            pending = {"name": line.split()[1]}
        elif line.startswith("//!SIZE") and pending is not None:
            pending["size"] = tuple(int(x) for x in line.split()[1:3])
        elif pending is not None and "size" in pending and not line.startswith("//!"):
            pending["hex"] = line.strip()
            tables.append(pending)
            pending = None
    if wanted >= len(tables):
        sys.stderr.write(f"{hook_path}: asked for table {wanted}, found {len(tables)}\n")
        return 1
    table = tables[wanted]
    width, height = table["size"]

    raw = binascii.unhexlify(table["hex"])
    expected = width * height * 4 * 4  # rgba, float32 each; see the docstring
    if len(raw) != expected:
        sys.stderr.write(
            f"{hook_path}: {len(raw)} bytes of table, expected {expected} "
            f"for {width}x{height} rgba float32\n")
        return 1

    count = len(raw) // 4
    values = struct.unpack("<" + "f" * count, raw)

    # float32 -> float16, checked. A weight that does not survive the
    # conversion is a filter that quietly stops matching its reference,
    # which is worse than a build that stops.
    halves = bytearray()
    worst_rel = 0.0
    worst_at = -1
    for i, v in enumerate(values):
        packed = struct.pack("<e", v)
        back = struct.unpack("<e", packed)[0]
        if back != back or (back in (float("inf"), float("-inf")) and v not in
                            (float("inf"), float("-inf"))):
            sys.stderr.write(f"{hook_path}: weight {i} ({v!r}) does not fit float16\n")
            return 1
        scale = max(abs(v), 1.0e-3)
        rel = abs(back - v) / scale
        if rel > worst_rel:
            worst_rel, worst_at = rel, i
        halves += packed
    if worst_rel > 1.0e-3:
        sys.stderr.write(
            f"{hook_path}: weight {worst_at} loses {worst_rel:.2e} of its magnitude "
            f"as float16, more than the 1e-3 this allows\n")
        return 1

    # Emitted as 32-bit words because that is what a uint32_t array in
    # the host wants; each holds two halves, little-endian.
    words = len(halves) // 4
    with open(out_path, "w") as out:
        out.write("// Generated by tools/gen_ravu_lut.py. Do not edit.\n")
        out.write(f"// RAVU-Zoom r2 {table['name']}, {width}x{height} rgba float16,\n")
        out.write(f"// packed two per word. Worst conversion error {worst_rel:.2e}.\n")
        out.write("{\n")
        for i in range(0, words, 8):
            chunk = halves[i * 4:(i + 8) * 4]
            vals = ["0x%08x" % int.from_bytes(chunk[j:j + 4], "little")
                    for j in range(0, len(chunk), 4)]
            out.write("    " + ",".join(vals) + ",\n")
        out.write("}\n")
    print(f"{out_path}: {table['name']}, {count} weights as float16 in {words} words, "
          f"{width}x{height}, worst error {worst_rel:.2e}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
