#!/usr/bin/env python3
"""Turns packaged PNG icons into the array _NET_WM_ICON wants.

X11 has no "point at this file" for a window icon: the property is raw
ARGB, width and height first, as an array of longs. So the icon has to be
in the binary, and this generates it at configure time from the same PNGs
the packages install. No second copy to keep in step, and no runtime
image decoder in a process that has no other use for one.

Only what these files actually are is handled: non-interlaced, 8-bit
RGBA or RGB. Anything else is an error rather than a guess. zlib is
stdlib, so this needs nothing installed.
"""

import struct
import sys
import zlib


def decode_png(path):
    data = open(path, "rb").read()
    if data[:8] != b"\x89PNG\r\n\x1a\n":
        raise SystemExit(f"{path}: not a PNG")
    pos = 8
    width = height = 0
    colour = bits = interlace = -1
    idat = bytearray()
    palette = b""
    while pos < len(data):
        (length,) = struct.unpack_from(">I", data, pos)
        kind = data[pos + 4 : pos + 8]
        body = data[pos + 8 : pos + 8 + length]
        pos += 12 + length
        if kind == b"IHDR":
            width, height, bits, colour, _, _, interlace = struct.unpack(">IIBBBBB", body)
        elif kind == b"PLTE":
            palette = body
        elif kind == b"IDAT":
            idat += body
        elif kind == b"IEND":
            break
    if interlace != 0 or bits != 8 or colour not in (2, 6, 3):
        raise SystemExit(f"{path}: only 8-bit non-interlaced RGB/RGBA/palette is handled "
                         f"(bits={bits} colour={colour} interlace={interlace})")

    channels = {2: 3, 6: 4, 3: 1}[colour]
    raw = zlib.decompress(bytes(idat))
    stride = width * channels
    out = bytearray()
    previous = bytearray(stride)
    at = 0
    for _ in range(height):
        filter_type = raw[at]
        at += 1
        line = bytearray(raw[at : at + stride])
        at += stride
        for i in range(stride):
            a = line[i - channels] if i >= channels else 0
            b = previous[i]
            c = previous[i - channels] if i >= channels else 0
            if filter_type == 1:
                line[i] = (line[i] + a) & 0xFF
            elif filter_type == 2:
                line[i] = (line[i] + b) & 0xFF
            elif filter_type == 3:
                line[i] = (line[i] + (a + b) // 2) & 0xFF
            elif filter_type == 4:
                p = a + b - c
                pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
                nearest = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + nearest) & 0xFF
            elif filter_type != 0:
                raise SystemExit(f"{path}: unknown row filter {filter_type}")
        out += line
        previous = line

    pixels = []
    for i in range(width * height):
        if colour == 3:
            index = out[i] * 3
            r, g, b, a = palette[index], palette[index + 1], palette[index + 2], 255
        elif channels == 4:
            r, g, b, a = out[i * 4 : i * 4 + 4]
        else:
            r, g, b = out[i * 3 : i * 3 + 3]
            a = 255
        pixels.append((a << 24) | (r << 16) | (g << 8) | b)
    return width, height, pixels


def main():
    output = sys.argv[1]
    values = []
    for path in sys.argv[2:]:
        width, height, pixels = decode_png(path)
        values += [width, height] + pixels
    with open(output, "w") as f:
        f.write("// Generated by tools/png_to_argb_header.py, do not edit.\n")
        f.write("// _NET_WM_ICON payload: width, height, then ARGB pixels, per size.\n")
        f.write("#pragma once\n\n#include <cstddef>\n\n")
        f.write("inline const unsigned long kStudWindowIcon[] = {\n")
        for i in range(0, len(values), 8):
            f.write("    " + ", ".join(f"0x{v:08x}ul" for v in values[i : i + 8]) + ",\n")
        f.write("};\n")
        f.write("inline constexpr size_t kStudWindowIconLength = "
                f"{len(values)};\n")


if __name__ == "__main__":
    main()
